{% set name = "awscli" %}
{% set version = "2.27.55" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/aws-cli/archive/{{ version }}.tar.gz
  sha256: efd5449c6d73752e62db36bbe24a72abd8bfda5c13d81be3bc35e59c429abc52
  patches:
    - patches/0001-fix-dependencies-version.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
    - mkdir -p $PREFIX/share/bash-completions/completions && echo complete -C aws_completer aws >$PREFIX/share/bash-completions/completions/aws  # [unix]
  # Drop Py3.13 due to missing dependency versions of ruamel.yaml/urllib3 for Py3.13. Remove it when upstream bump dependency versions
  skip: True  # [py<39 or py>312]

requirements:
  build:
    - patch  # [not win]
    - msys2-patch  # [win]
  host:
    - python
    - pip
    - flit-core >=3.7.1,<3.9.1
    # The build process generates the autocomplete index (scripts/gen-ac-index)
    # which requires importing awscli modules, so we need to install all runtime
    # dependencies too. YAML anchors don't support merging lists so we have to
    # duplicate everything :-(
    - colorama >=0.2.5,<0.4.7
    - docutils >=0.10,<0.20
    - ruamel.yaml >=0.15.0,<=0.17.21
    - ruamel.yaml.clib >=0.2.0,<=0.2.12
    - prompt-toolkit >=3.0.24,<3.0.39
    - distro >=1.5.0,<1.9.0
    - awscrt >=0.26.1
    - python-dateutil >=2.1,<=2.9.0
    - jmespath >=0.7.1,<1.1.0
    - urllib3 >=1.25.4,<1.27
  run:
    - python
    - colorama >=0.2.5,<0.4.7
    - docutils >=0.10,<0.20
    - ruamel.yaml >=0.15.0,<=0.17.21
    - ruamel.yaml.clib >=0.2.0,<=0.2.12
    - prompt-toolkit >=3.0.24,<3.0.39
    - distro >=1.5.0,<1.9.0
    - awscrt >=0.26.1
    - python-dateutil >=2.1,<=2.9.0
    - jmespath >=0.7.1,<1.1.0
    - urllib3 >=1.25.4,<1.27

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - jsonschema >=4.7.2
  imports:
    - awscli
    - awscli.alias
    - awscli.argparser
    - awscli.argprocess
    - awscli.arguments
    - awscli.autocomplete
    - awscli.autocomplete.local
    - awscli.autocomplete.serverside
    - awscli.autocomplete.serverside.custom_completers
    - awscli.autocomplete.serverside.custom_completers.ddb
    - awscli.autocomplete.serverside.custom_completers.logs
    - awscli.autoprompt
    - awscli.bcdoc
    - awscli.botocore
    - awscli.botocore.awsrequest
    - awscli.botocore.session
    - awscli.botocore.crt
    - awscli.botocore.docs
    - awscli.botocore.docs.bcdoc
    - awscli.botocore.retries
    - awscli.botocore.vendored
    - awscli.botocore.vendored.requests
    - awscli.botocore.vendored.requests.packages
    - awscli.botocore.vendored.requests.packages.urllib3
    - awscli.clidocs
    - awscli.clidriver
    - awscli.commands
    - awscli.compat
    - awscli.constants
    - awscli.customizations
    - awscli.customizations.cloudformation
    - awscli.customizations.cloudtrail
    - awscli.customizations.codeartifact
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.dlm
    - awscli.customizations.dynamodb
    - awscli.customizations.ec2
    - awscli.customizations.ec2instanceconnect
    - awscli.customizations.ecs
    - awscli.customizations.eks
    - awscli.customizations.emr
    - awscli.customizations.emrcontainers
    - awscli.customizations.gamelift
    - awscli.customizations.history
    - awscli.customizations.lightsail
    - awscli.customizations.logs
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy
    - awscli.customizations.servicecatalog
    - awscli.customizations.sso
    - awscli.customizations.wizard
    - awscli.customizations.wizard.ui
    - awscli.s3transfer
    - awscli.errorhandler
    - awscli.formatter
    - awscli.help
    - awscli.logger
    - awscli.paramfile
    - awscli.plugin
    - awscli.schema
    - awscli.shorthand
    - awscli.table
    - awscli.telemetry
    - awscli.testutils
    - awscli.topictags
    - awscli.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - aws --version
    - aws_completer --help
    # Check autocomplete index exists:
    - python -c "import awscli, os; assert os.stat(os.path.join(os.path.dirname(awscli.__file__), 'data', 'ac.index')).st_size > 1e6"
    - COMP_LINE="aws ec2 describe-inst" aws_completer  # [unix]
    # Skip upstream tests because they take several hours to run on CI.

about:
  home: https://aws.amazon.com/cli
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  description: This package provides a unified command line interface to Amazon Web Services.
  dev_url: https://github.com/aws/aws-cli/tree/v2
  doc_url: https://aws.amazon.com/cli

extra:
  recipe-maintainers:
    - xhochy
    - tkelman
  skip-lints:
    # Use newer version of Win patch
    - patch_must_be_in_build
